site_name: JustLend DAO Documentation
# site_url: https://docs.justlend.org/

nav:
    - GETTING STARTED:
        - Overview: getting_started/overview.md
        - Concepts:
            - Supply: getting_started/concepts/supply.md
            - Borrow: getting_started/concepts/borrow.md
            - Withdraw: getting_started/concepts/withdraw.md
            - Repay: getting_started/concepts/repay.md
            - Liquidations: getting_started/concepts/liquidations.md
            - Risks: getting_started/concepts/risks.md
            - Staked TRX: getting_started/concepts/staked_trx.md
            - Energy Rental: getting_started/concepts/energy_rental.md
        - Whitepaper: https://justlend.org/docs/justlend_whitepaper_en.pdf
        - FAQs:
            - Wallet Connection Questions: getting_started/faqs/wallet_connection_questions.md
            - Spending Cap Issue During Transactions: getting_started/faqs/spending_cap_issue.md
            - More Questions: https://support.justlend.org/hc/en-us/sections/360011389611-Questions
    - GOVERNANCE:
        - JIPs: governance/jips.md
        - Tokenomics: governance/tokenomics.md
        - Community Forum: https://forum.justlend.org
    - DEVELOPERS:
        - Contracts Overview: developers/contracts_overview.md
        - Supply and Borrow Market:
            - SBM: developers/supply_and_borrow_market/sbm.md
            - Interest Rate Model: developers/supply_and_borrow_market/interest_rate_model.md
            - Governance: developers/supply_and_borrow_market/governance.md
            - Price Oracle: developers/supply_and_borrow_market/price_oracle.md
            - Comptroller: developers/supply_and_borrow_market/comptroller.md
        - Staked TRX: developers/staked_trx.md
        - Energy Rental: developers/energy_rental.md
        - Deployed Contracts: developers/deployed_contracts.md
        - APIs: developers/apis.md
    - RESOURCES:
        - Community:
            - Links: resources/community/links.md
            - Wallet Integration Cooperation: resources/community/wallet_integration_cooperation.md
        - Risk Warning: resources/risk_warning.md
        - Audits:
            - Supply & Borrow: https://justlend.org/docs/justlend_audit_en.pdf
            - Staked TRX: https://justlend.org/docs/justlend_strx_audit_en.pdf
        - Terms of Service:
            - Terms of Service: https://justlend.org/docs/JustLend_Terms_of_Use_en.pdf
            - Privacy Policy: https://justlend.org/docs/JustLend_Privacy_Policy_en.pdf


theme:
    name: material
    custom_dir: docs/overrides
    features:
        - navigation.sections
        - toc.integrate
        - search.highlight
        - search.suggest
        - content.code.annotate
        - content.tooltips

extra_css:
        - stylesheets/extra.css
        - stylesheets/hide_elements.css

plugins:
      - search
      - swagger-ui-tag # 添加这个插件

markdown_extensions:
        - admonition
        - codehilite
        - toc:
            permalink: true
            toc_depth: 3
        - pymdownx.arithmatex
        - pymdownx.tilde
        - pymdownx.tasklist
        - pymdownx.superfences
